package pl.wiktor.management.model.enums;

public enum RoleEnum {
    /* DEFAULT ROLE WITHOUT ANY PRIVILEGES AND VIEWS */
    USER,
    /* CAN MANAGE USERS AND PATIENTS ONLY */
    ADMINISTRATOR,
    /* CAN ACCESS TO WORK LIST: CAN REGISTER NEW PATIENT, CAN REQUEST EXAMINATION, MAKE EXAMINATION, DO DESCRIPTION RESULT */
    DOCTOR,
    /* CAN ACCESS TO WORK LIST: CAN REGISTER NEW PATIENT, MAKE AN EXAMINATION */
    TECHNICAN
}
